// Style Dictionary v5 build. Emits three artifacts under dist/:
//   - tokens.scss : Sass variables ($brand-green-500: ...;)
//   - tokens.css  : CSS custom properties (:root { --brand-green-500: ...; })
//   - tokens.ts   : Typed nested const + Tokens type (export const tokens = { ... } as const)
//
// Run via `pnpm --filter @repo/design-tokens build` or as the `prepare` hook on install.

import StyleDictionary from "style-dictionary";
import { fileURLToPath } from "node:url";
import { dirname } from "node:path";
import { posix } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
// Style Dictionary v5 expects POSIX-style globs; convert Windows backslashes.
const toPosix = (p) => p.split("\\").join("/");
const ROOT = toPosix(__dirname);

// Recursively walks the SD nested token tree and replaces each leaf
// ({ value, type, name, ... }) with its raw value, so the result is a plain
// nested JS object ready for JSON.stringify + `as const`.
function extractValues(node) {
  if (node === null || typeof node !== "object") return node;
  if ("value" in node && typeof node.value !== "object") {
    return node.value;
  }
  const out = {};
  for (const key of Object.keys(node)) {
    if (key === "attributes" || key === "original" || key === "$type") continue;
    out[key] = extractValues(node[key]);
  }
  return out;
}

StyleDictionary.registerFormat({
  name: "typescript/nested-const",
  format: ({ dictionary }) => {
    const nested = extractValues(dictionary.tokens);
    return [
      "// AUTO-GENERATED by Style Dictionary. Do not edit by hand.",
      "// Source: packages/design-tokens/src/tokens/*.json",
      "",
      `export const tokens = ${JSON.stringify(nested, null, 2)} as const;`,
      "",
      "export type Tokens = typeof tokens;",
      "",
    ].join("\n");
  },
});

const sd = new StyleDictionary({
  source: [posix.join(ROOT, "src/tokens/**/*.json")],
  platforms: {
    scss: {
      transformGroup: "scss",
      buildPath: posix.join(ROOT, "dist") + "/",
      files: [
        {
          destination: "tokens.scss",
          format: "scss/variables",
          options: { outputReferences: false },
        },
      ],
    },
    css: {
      transformGroup: "css",
      buildPath: posix.join(ROOT, "dist") + "/",
      files: [
        {
          destination: "tokens.css",
          format: "css/variables",
          options: { outputReferences: false, selector: ":root" },
        },
      ],
    },
    ts: {
      transformGroup: "js",
      buildPath: posix.join(ROOT, "dist") + "/",
      files: [
        {
          destination: "tokens.ts",
          format: "typescript/nested-const",
        },
      ],
    },
  },
  log: { warnings: "warn", verbosity: "default" },
});

await sd.cleanAllPlatforms();
await sd.buildAllPlatforms();
