import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Schema as MongooseSchema } from 'mongoose';

/**
 * Embedded product variant subdoc. Per phase-7 D3 / Q2: variants live
 * as a Mongoose subdoc-array on the parent product
 * (`product.products[variants]`), with `attributes` as a free-form
 * Map<string, string> capturing arbitrary `{ color: 'Black', size:
 * 'M' }` shapes.
 *
 * SKU uniqueness is enforced at the service layer (across all variants
 * of a single product) since a Mongo unique index on a subdoc-array
 * field isn't well-supported across the array's full enumeration.
 *
 * 200-variant cap per product per D18 — variant.service throws
 * `VARIANT_LIMIT_EXCEEDED` above that.
 */

@Schema({ _id: false })
export class VariantDimensions {
  @Prop({ required: true, type: Number, min: 1, max: 2_000 })
  lengthMm!: number;

  @Prop({ required: true, type: Number, min: 1, max: 2_000 })
  widthMm!: number;

  @Prop({ required: true, type: Number, min: 1, max: 2_000 })
  heightMm!: number;
}

export const VariantDimensionsSchema = SchemaFactory.createForClass(VariantDimensions);

@Schema({ _id: false })
export class Variant {
  /**
   * Variant id is a ULID generated by the service layer (not Mongo's
   * subdoc `_id`) so it round-trips through the outbox events + the
   * read-side `product.search_index` collection without re-serialization.
   */
  @Prop({ required: true, type: String, index: true })
  id!: string;

  @Prop({ required: true, type: String, trim: true, uppercase: true })
  sku!: string;

  /**
   * Variant attributes — free-form `Map<string, string>`. Validated at
   * the service layer to have 1-12 entries with each value ≤120 chars
   * (mirrors `VariantAttributesSchema`).
   */
  @Prop({ required: true, type: MongooseSchema.Types.Mixed, default: {} })
  attributes!: Record<string, string>;

  @Prop({ required: true, type: Number, min: 0 })
  pricePaise!: number;

  @Prop({ required: true, type: Number, min: 1, max: 50_000 })
  weightGrams!: number;

  @Prop({ required: true, type: VariantDimensionsSchema })
  dimensionsMm!: VariantDimensions;

  @Prop({ type: String, default: null })
  barcode!: string | null;

  @Prop({ required: true, type: Boolean, default: true })
  enabled!: boolean;

  @Prop({ type: Date, default: Date.now })
  createdAt!: Date;

  @Prop({ type: Date, default: Date.now })
  updatedAt!: Date;
}

export const VariantSchema = SchemaFactory.createForClass(Variant);
