# scripts/refresh-project-fields-and-items.ps1
# Updates single-select field options with rich descriptions + brand colours on the
# LotusGift GitHub Project v2 (project #9, owner goldr0g3r).
#
# Usage:
#   .\scripts\refresh-project-fields-and-items.ps1
#
# Prerequisites:
#   - gh CLI installed + authenticated with `project` scope.
#   - Field IDs captured from `gh project field-list 9 --owner goldr0g3r`.
#
# This script:
#   1. Updates every single-select field's options with rich descriptions + colours.
#   2. The option IDs are regenerated by GitHub after the update.

param(
    [string]$Repo = "goldr0g3r/lotusgift",
    [string]$Owner = "goldr0g3r",
    [int]$ProjectNumber = 9,
    [string]$ProjectId = "PVT_kwHOB9XnOc4BXcKj"
)

$ErrorActionPreference = "Stop"

# Field IDs from `gh project field-list 9 --owner goldr0g3r`.
$FieldIds = @{
    Status    = "PVTSSF_lAHOB9XnOc4BXcKjzhSo_w0"
    Phase     = "PVTSSF_lAHOB9XnOc4BXcKjzhSpAJ8"
    Team      = "PVTSSF_lAHOB9XnOc4BXcKjzhSo_7E"
}

# Note: We need to create the Type, Workstream, Priority fields if they don't exist.
# For now, update the fields that DO exist (Phase).

# Valid colour enum (GitHub ProjectV2SingleSelectFieldOptionColor):
#   GRAY, BLUE, GREEN, YELLOW, ORANGE, RED, PINK, PURPLE

$FieldOptionSpec = @{
    Phase = @(
        @{ name = "P0";  color = "PURPLE"; description = "Foundation Reset -- cursor rules + skills + GitHub templates + research stubs + workspace bootstrap" }
        @{ name = "P1";  color = "PURPLE"; description = "L0 Packages -- @repo/typescript-config, @repo/eslint-config, @repo/prettier-config, @repo/jest-config" }
        @{ name = "P2";  color = "PURPLE"; description = "L1 Contracts -- @repo/types, @repo/validators, @repo/events, @repo/openapi-spec" }
        @{ name = "P3";  color = "PURPLE"; description = "L2 Infra + Analytics -- @repo/database + @repo/config + @repo/utils + @repo/observability + @repo/analytics-sdk + @repo/feature-flags" }
        @{ name = "P4";  color = "BLUE";   description = "API Gateway -- NestJS modular-monolith shell + OpenAPI + Swagger" }
        @{ name = "P5";  color = "BLUE";   description = "Auth Service -- Better-Auth + passkey + 2FA + phone OTP + Google social + email-verify" }
        @{ name = "P6";  color = "BLUE";   description = "Vendor Service -- onboarding + KYC + multi-warehouse + vendor tiers + payout config" }
        @{ name = "P7";  color = "BLUE";   description = "Product Service -- taxonomy + R2 uploads + Atlas Search + variants + SKU" }
        @{ name = "P8";  color = "BLUE";   description = "Inventory + Customization -- stock ledger + Redis reservations + art upload + mockup + approval" }
        @{ name = "P9";  color = "BLUE";   description = "Order + RFQ + Recipient-List -- auto-router + RFQ workflow + CSV drop-shipping" }
        @{ name = "P10"; color = "BLUE";   description = "Payment Service -- Razorpay (UPI/cards/netbanking/wallets) + webhooks + idempotency + PO/credit" }
        @{ name = "P11"; color = "BLUE";   description = "Shipping Service -- multi-carrier + tracking + recipient-list fulfillment" }
        @{ name = "P12"; color = "GREEN";  description = "Notification Service -- Resend email + MSG91 SMS + WhatsApp templates" }
        @{ name = "P13"; color = "GREEN";  description = "Tax Service -- GST + HSN/SAC + compliance" }
        @{ name = "P14"; color = "GREEN";  description = "Promotions Service -- coupons + bulk discounts + corporate pricing" }
        @{ name = "P15"; color = "GREEN";  description = "Insights Service -- reporting + analytics + dashboards" }
        @{ name = "P16"; color = "YELLOW"; description = "Web Customer App -- Next.js App Router + SSR catalog + cart + checkout" }
        @{ name = "P17"; color = "YELLOW"; description = "Web Vendor App -- dashboard + products + orders + payouts" }
        @{ name = "P18"; color = "YELLOW"; description = "Web Admin App -- platform admin + analytics + moderation" }
        @{ name = "P19"; color = "YELLOW"; description = "Web Customer Service App -- tickets + chat + escalation" }
        @{ name = "P20"; color = "GREEN";  description = "Review + Support Services -- product reviews + ratings + support tickets" }
        @{ name = "P21"; color = "ORANGE"; description = "Observability Hardening -- Sentry + Grafana + OTEL + alerts + SLOs" }
        @{ name = "P22"; color = "RED";    description = "Launch -- Oracle production deploy + Vercel + monitoring + soft-launch" }
    )
    Status = @(
        @{ name = "Backlog";     color = "GRAY";   description = "Not yet triaged or scheduled" }
        @{ name = "Todo";        color = "BLUE";   description = "Triaged and ready to be picked up this phase" }
        @{ name = "Ready";       color = "GREEN";  description = "All prerequisites met, ready to start" }
        @{ name = "In progress"; color = "YELLOW"; description = "Actively being worked on" }
        @{ name = "In review";   color = "ORANGE"; description = "PR open, awaiting CI + review" }
        @{ name = "Blocked";     color = "RED";    description = "Blocked on external dependency or decision" }
        @{ name = "Done";        color = "PURPLE"; description = "Shipped and verified" }
    )
}

# ---------------------------------------------------------------------------
# GraphQL mutation to update single-select field options
# ---------------------------------------------------------------------------

$mutation = @'
mutation($fid: ID!, $opts: [ProjectV2SingleSelectFieldOptionInput!]) {
  updateProjectV2Field(input: { fieldId: $fid, singleSelectOptions: $opts }) {
    projectV2Field {
      ... on ProjectV2SingleSelectField {
        id
        name
        options { id name description }
      }
    }
  }
}
'@

Write-Host "==> Updating single-select fields with rich descriptions + colours"
foreach ($fieldName in $FieldOptionSpec.Keys) {
    $fieldId = $FieldIds[$fieldName]
    if (-not $fieldId) {
        Write-Host "  ! Field ID not configured for: $fieldName (skipping)"
        continue
    }
    $opts = $FieldOptionSpec[$fieldName]
    $payload = @{ query = $mutation; variables = @{ fid = $fieldId; opts = $opts } } | ConvertTo-Json -Depth 8
    $tmp = [System.IO.Path]::GetTempFileName()
    [System.IO.File]::WriteAllText($tmp, $payload, [System.Text.UTF8Encoding]::new($false))
    $result = gh api graphql --input "$tmp" 2>&1
    Remove-Item $tmp
    $parsed = $result | ConvertFrom-Json
    if ($parsed.errors) {
        Write-Host "  ! FAILED: $fieldName -- $($parsed.errors | ConvertTo-Json -Compress)"
        continue
    }
    $newOpts = $parsed.data.updateProjectV2Field.projectV2Field.options
    Write-Host "  ~ updated: $fieldName ($($newOpts.Count) options w/ descriptions + colours)"
}

# ---------------------------------------------------------------------------
# Phase schedule -- Start/Target dates per phase.
# ---------------------------------------------------------------------------
$PhaseSchedule = @{
    P0  = @{ Start = "2026-05-12"; Target = "2026-05-14" }
    P1  = @{ Start = "2026-05-14"; Target = "2026-05-16" }
    P2  = @{ Start = "2026-05-16"; Target = "2026-05-17" }
    P3  = @{ Start = "2026-05-17"; Target = "2026-05-18" }
    P4  = @{ Start = "2026-05-18"; Target = "2026-05-19" }
    P5  = @{ Start = "2026-05-19"; Target = "2026-05-20" }
    P6  = @{ Start = "2026-05-20"; Target = "2026-05-22" }
    P7  = @{ Start = "2026-05-22"; Target = "2026-05-24" }
    P8  = @{ Start = "2026-05-24"; Target = "2026-05-26" }
    P9  = @{ Start = "2026-05-26"; Target = "2026-05-30" }
    P10 = @{ Start = "2026-05-30"; Target = "2026-06-02" }
    P11 = @{ Start = "2026-06-02"; Target = "2026-06-05" }
    P12 = @{ Start = "2026-06-05"; Target = "2026-06-08" }
    P13 = @{ Start = "2026-06-08"; Target = "2026-06-10" }
    P14 = @{ Start = "2026-06-10"; Target = "2026-06-13" }
    P15 = @{ Start = "2026-06-13"; Target = "2026-06-16" }
    P16 = @{ Start = "2026-06-16"; Target = "2026-06-30" }
    P17 = @{ Start = "2026-06-30"; Target = "2026-07-14" }
    P18 = @{ Start = "2026-07-14"; Target = "2026-07-28" }
    P19 = @{ Start = "2026-07-28"; Target = "2026-08-11" }
    P20 = @{ Start = "2026-08-11"; Target = "2026-08-18" }
    P21 = @{ Start = "2026-08-18"; Target = "2026-08-25" }
    P22 = @{ Start = "2026-08-25"; Target = "2026-09-01" }
}

Write-Host ""
Write-Host "==> Done. Phase schedule defined for Start/Target date population."
Write-Host "    Run scripts/seed-project-issues.ps1 to create review issues and set field values."
Write-Host "    Project: https://github.com/users/$Owner/projects/$ProjectNumber"
